package abb;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class FrmPrincipal extends javax.swing.JFrame {

    PersonaVotante personaVotante;
    ArbolBinarioBusqueda abb;
    Connection reg;

    public FrmPrincipal() {

        initComponents();
        abb = new ArbolBinarioBusqueda();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel12 = new javax.swing.JLabel();
        cbGenero1 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre1 = new javax.swing.JTextField();
        txtFechaNacimiento1 = new javax.swing.JTextField();
        txtMesa1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jlabel6 = new javax.swing.JLabel();
        txtCodigoProvincia = new javax.swing.JLabel();
        txtCodigoCanton = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtRecinto1 = new javax.swing.JTextField();
        btnIngresar1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        cbCanton = new javax.swing.JComboBox();
        cbProvincia = new javax.swing.JComboBox();
        cbParroquia = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaResultado = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        PreRecursivo1 = new javax.swing.JMenu();
        PreRecursivo = new javax.swing.JMenuItem();
        PreNoRecursivo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        PosRecursivo = new javax.swing.JMenuItem();
        PosNoRecursivo = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        InRecursivo = new javax.swing.JMenuItem();
        InNoRecursivo = new javax.swing.JMenuItem();
        Niveles = new javax.swing.JMenuItem();

        jLabel12.setText("Recinto:");

        cbGenero1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MASCULINO", "FEMENINO" }));
        cbGenero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGenero1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Lugar y fecha de nacimiento:");

        jLabel14.setText("Genero:");

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        jLabel15.setText("Cedula:");

        jlabel6.setText("Nombre");

        txtCodigoProvincia.setText("Cod Provincia:");

        txtCodigoCanton.setText("Cod Canton:");

        jLabel19.setText("Cod Parroquia:");

        jLabel20.setText("Mesa:");

        btnIngresar1.setText("Guardar");
        btnIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar1ActionPerformed(evt);
            }
        });

        btnCancelar1.setText("Guardar sin cambios");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        cbCanton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCantonActionPerformed(evt);
            }
        });

        cbProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProvinciaActionPerformed(evt);
            }
        });

        cbParroquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbParroquiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngresar1)
                .addGap(72, 72, 72)
                .addComponent(btnCancelar1)
                .addGap(111, 111, 111))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCanton, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbParroquia, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jlabel6)
                                .addComponent(txtCodigoProvincia)
                                .addComponent(txtCodigoCanton)
                                .addComponent(jLabel19))
                            .addGap(44, 44, 44)
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombre1)
                                .addComponent(txtCedula)))
                        .addGroup(jFrame1Layout.createSequentialGroup()
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jFrame1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(28, 28, 28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrame1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jFrame1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(77, 77, 77)))
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbGenero1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFechaNacimiento1)
                                .addComponent(txtRecinto1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(37, Short.MAX_VALUE)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(cbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbParroquia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar1)
                    .addComponent(btnCancelar1))
                .addGap(27, 27, 27))
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlabel6)
                        .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(txtCodigoProvincia)
                    .addGap(18, 18, 18)
                    .addComponent(txtCodigoCanton)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel19)
                    .addGap(18, 18, 18)
                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtRecinto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(44, 44, 44)
                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtFechaNacimiento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(cbGenero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(100, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PERSONAS VOTANTES");

        jLabel2.setText("Realizado Por: Gabriela Carrión y Santiago Lomas");

        btnIngresar.setText("NUEVO");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        txaResultado.setColumns(20);
        txaResultado.setRows(5);
        jScrollPane1.setViewportView(txaResultado);

        jButton1.setText("CONECTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("RECUPERAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("Recorridos");

        PreRecursivo1.setText("Preorder");

        PreRecursivo.setText("Recursivo");
        PreRecursivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreRecursivoActionPerformed(evt);
            }
        });
        PreRecursivo1.add(PreRecursivo);

        PreNoRecursivo.setText("No Recursivo");
        PreNoRecursivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreNoRecursivoActionPerformed(evt);
            }
        });
        PreRecursivo1.add(PreNoRecursivo);

        jMenu1.add(PreRecursivo1);

        jMenu3.setText("Posorder");

        PosRecursivo.setText("Recursivo");
        PosRecursivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PosRecursivoActionPerformed(evt);
            }
        });
        jMenu3.add(PosRecursivo);

        PosNoRecursivo.setText("No Recursivo");
        PosNoRecursivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PosNoRecursivoActionPerformed(evt);
            }
        });
        jMenu3.add(PosNoRecursivo);

        jMenu1.add(jMenu3);

        jMenu5.setText("Inorder");

        InRecursivo.setText(" Recursivo");
        InRecursivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InRecursivoActionPerformed(evt);
            }
        });
        jMenu5.add(InRecursivo);

        InNoRecursivo.setText("No Recursivo");
        InNoRecursivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InNoRecursivoActionPerformed(evt);
            }
        });
        jMenu5.add(InNoRecursivo);

        jMenu1.add(jMenu5);

        Niveles.setText("Niveles");
        Niveles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NivelesActionPerformed(evt);
            }
        });
        jMenu1.add(Niveles);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIngresar)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(jLabel1)
                                        .addGap(57, 57, 57))
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jButton1)
                                .addGap(17, 17, 17)
                                .addComponent(jButton2)))
                        .addGap(0, 354, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        jFrame1.setVisible(true);
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void cbGenero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGenero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGenero1ActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void btnIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar1ActionPerformed
        if (abb.VerificarCedula(txtCedula.getText()) == true) {
            JOptionPane.showMessageDialog(null, "Cedula Valida ");
            String sql;
            String mensaje = "";
            reg = abb.conexion();
            try {
                personaVotante = new PersonaVotante(txtCedula.getText(), txtNombre1.getText(), (cbProvincia.getSelectedItem() + ""), (cbCanton.getSelectedItem() + ""), (cbParroquia.getSelectedItem() + ""), txtRecinto1.getText(), Integer.parseInt(txtMesa1.getText()), txtFechaNacimiento1.getText(), (cbGenero1.getSelectedItem() + ""));
                if (cbProvincia.getSelectedIndex() >= 0 && cbCanton.getSelectedIndex() >= 0 && cbParroquia.getSelectedIndex() >= 0) {
                String ced = txtCedula.getText();
                String nom = txtNombre1.getText();
                String cP = ((Provincia) cbProvincia.getSelectedItem()).getCodigo();
                String cC = ((Canton) cbCanton.getSelectedItem()).getCodigo();
                String cPa = ((Parroquia) cbParroquia.getSelectedItem()).getCodigo();
                String reci = txtRecinto1.getText();
                String mesa = txtMesa1.getText();
                String Fech = txtFechaNacimiento1.getText();
                String gen = (cbGenero1.getSelectedItem() + "");

                sql = "INSERT INTO persona(cedula,nombre,codProvincia,codCanton,codParroquia,recinto,mesa,fecha_nacimiento,genero)VALUES (?,?,?,?,?,?,?,?,?)";
                try {
                    PreparedStatement pst = reg.prepareStatement(sql);
                    pst.setString(1, ced);
                    pst.setString(2, nom);
                    pst.setString(3, cP);
                    pst.setString(4, cC);
                    pst.setString(5, cPa);
                    pst.setString(6, reci);
                    pst.setString(7, mesa);
                    pst.setString(8, Fech);
                    pst.setString(9, gen);
                    int n = pst.executeUpdate();
                    if (n > 0) {
                        mensaje = "SI";
                        JOptionPane.showMessageDialog(null, "registrado con exito");
                    }

                } catch (SQLException ex) {
                    mensaje = "NO";
                    Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "revise que los datos sean correctos");
            }
            cbProvincia.setSelectedIndex(0);
            txtMesa1.setText("");
            txtRecinto1.setText("");
            cbGenero1.setSelectedIndex(0);
            txtFechaNacimiento1.setText("");
            txtNombre1.setText("");
            cbParroquia.setSelectedIndex(0);
            cbCanton.setSelectedIndex(0);
            txtCedula.setText("");
            jFrame1.setVisible(false);
            
            

        } else {
            JOptionPane.showMessageDialog(null, "cedula Invalida ");
        }

    }//GEN-LAST:event_btnIngresar1ActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        cbCanton.setSelectedIndex(0);
        txtMesa1.setText("");
        txtRecinto1.setText("");
        cbGenero1.setSelectedIndex(0);
        txtFechaNacimiento1.setText("");
        txtNombre1.setText("");
        cbParroquia.setSelectedIndex(0);
        cbProvincia.setSelectedIndex(0);
        txtCedula.setText("");
        jFrame1.setVisible(false);
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        reg = abb.conexion();
        try {
            PreparedStatement pst = reg.prepareStatement("SELECT * FROM provincia");
            ResultSet provincias = pst.executeQuery();
            while (provincias.next()) {
                Provincia provincia = new Provincia();
                provincia.setCodigo(provincias.getNString("cod_Provincia"));
                provincia.setNombre(provincias.getNString("provincia"));
                cbProvincia.addItem(provincia);
            }
            provincias.close();
        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }



    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            reg = abb.conexion();
            PreparedStatement pst = reg.prepareStatement("select cedula, nombre, pro.provincia as provincia, c.canton as canton, pa.parroquia as parroquia, recinto, mesa, fecha_nacimiento, genero "
                    + "from persona p, provincia pro, canton c, parroquia pa "
                    + "where p.codProvincia=pro.cod_Provincia and c.cod_Canton=p.codCanton and pa.cod_Parroquia=p.codParroquia;");
            ResultSet resultado = pst.executeQuery();
            while (resultado.next()) {
                personaVotante = new PersonaVotante(resultado.getNString("cedula"), resultado.getNString("nombre"), resultado.getNString("provincia"), resultado.getNString("canton"), resultado.getNString("parroquia"), resultado.getNString("recinto"), Integer.parseInt(resultado.getNString("mesa")), resultado.getNString("fecha_nacimiento"), resultado.getNString("genero"));
                abb.ingresar(personaVotante);

            }
            resultado.close();

        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProvinciaActionPerformed
        cbCanton.removeAllItems();
        if (cbProvincia.getSelectedIndex() >= 0) {
            Provincia provincia = (Provincia) cbProvincia.getSelectedItem();
            try {
                PreparedStatement pst = reg.prepareStatement("SELECT * FROM canton where cod_Provincia='" + provincia.getCodigo() + "';");
                ResultSet cantones = pst.executeQuery();

                while (cantones.next()) {
                    Canton canton = new Canton();
                    canton.setCodigo(cantones.getNString("cod_Canton"));
                    canton.setNombre(cantones.getNString("canton"));
                    cbCanton.addItem(canton);
                }
                cantones.close();
            } catch (SQLException ex) {
                Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbProvinciaActionPerformed

    private void cbParroquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbParroquiaActionPerformed
    }//GEN-LAST:event_cbParroquiaActionPerformed

    private void cbCantonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCantonActionPerformed
        cbParroquia.removeAllItems();
        if (cbCanton.getSelectedIndex() >= 0) {
            Canton canton = (Canton) cbCanton.getSelectedItem();
            try {
                PreparedStatement pst = reg.prepareStatement("SELECT * FROM parroquia where cod_Canton='" + canton.getCodigo() + "';");
                ResultSet parroquias = pst.executeQuery();
                while (parroquias.next()) {
                    Parroquia parroquia = new Parroquia();
                    parroquia.setCodigo(parroquias.getNString("cod_Parroquia"));
                    parroquia.setNombre(parroquias.getNString("parroquia"));
                    cbParroquia.addItem(parroquia);
                }
                parroquias.close();
            } catch (SQLException ex) {
                Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbCantonActionPerformed

    private void PreRecursivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreRecursivoActionPerformed
        txaResultado.setText("Cedula" + "\t" + "Nombre" + "\t" + "CodProvincia" + "\t" + "CodCanton" + "\t" + "CodParroquia" + "\t" + "recinto" + "\t" + "mesa" + "\t" + "fechaNacimiento" + "\t" + "genero" + "\n" + abb.PreOrden(abb.raiz));
    }//GEN-LAST:event_PreRecursivoActionPerformed

    private void PreNoRecursivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreNoRecursivoActionPerformed
        txaResultado.setText("Cedula" + "\t" + "Nombre" + "\t" + "CodProvincia" + "\t" + "CodCanton" + "\t" + "CodParroquia" + "\t" + "recinto" + "\t" + "mesa" + "\t" + "fechaNacimiento" + "\t" + "genero" + "\n" + abb.PreOrderNoRecursivo(abb.raiz));
    }//GEN-LAST:event_PreNoRecursivoActionPerformed

    private void PosRecursivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PosRecursivoActionPerformed
        txaResultado.setText("Cedula" + "\t" + "Nombre" + "\t" + "CodProvincia" + "\t" + "CodCanton" + "\t" + "CodParroquia" + "\t" + "recinto" + "\t" + "mesa" + "\t" + "fechaNacimiento" + "\t" + "genero" + "\n" + abb.postorder(abb.raiz));
    }//GEN-LAST:event_PosRecursivoActionPerformed

    private void PosNoRecursivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PosNoRecursivoActionPerformed
        txaResultado.setText("Cedula" + "\t" + "Nombre" + "\t" + "CodProvincia" + "\t" + "CodCanton" + "\t" + "CodParroquia" + "\t" + "recinto" + "\t" + "mesa" + "\t" + "fechaNacimiento" + "\t" + "genero" + "\n" + abb.PosOrderNoRecursivo(abb.raiz));
    }//GEN-LAST:event_PosNoRecursivoActionPerformed

    private void InRecursivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InRecursivoActionPerformed
        txaResultado.setText("Cedula" + "\t" + "Nombre" + "\t" + "CodProvincia" + "\t" + "CodCanton" + "\t" + "CodParroquia" + "\t" + "recinto" + "\t" + "mesa" + "\t" + "fechaNacimiento" + "\t" + "genero" + "\n" + abb.InOrden(abb.raiz));
    }//GEN-LAST:event_InRecursivoActionPerformed

    private void InNoRecursivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InNoRecursivoActionPerformed
        txaResultado.setText("Cedula" + "\t" + "Nombre" + "\t" + "CodProvincia" + "\t" + "CodCanton" + "\t" + "CodParroquia" + "\t" + "recinto" + "\t" + "mesa" + "\t" + "fechaNacimiento" + "\t" + "genero" + "\n" + abb.InOrderNoRecursivo(abb.raiz));
    }//GEN-LAST:event_InNoRecursivoActionPerformed

    private void NivelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NivelesActionPerformed
        try {
            txaResultado.setText("Cedula" + "\t" + "Nombre" + "\t" + "CodProvincia" + "\t" + "CodCanton" + "\t" + "CodParroquia" + "\t" + "recinto" + "\t" + "mesa" + "\t" + "fechaNacimiento" + "\t" + "genero" + "\n" + abb.arbolrecorridoanch(abb.raiz));
        } catch (InterruptedException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_NivelesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem InNoRecursivo;
    private javax.swing.JMenuItem InRecursivo;
    private javax.swing.JMenuItem Niveles;
    private javax.swing.JMenuItem PosNoRecursivo;
    private javax.swing.JMenuItem PosRecursivo;
    private javax.swing.JMenuItem PreNoRecursivo;
    private javax.swing.JMenuItem PreRecursivo;
    private javax.swing.JMenu PreRecursivo1;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnIngresar1;
    private javax.swing.JComboBox cbCanton;
    private javax.swing.JComboBox cbGenero1;
    private javax.swing.JComboBox cbParroquia;
    private javax.swing.JComboBox cbProvincia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JTextArea txaResultado;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JLabel txtCodigoCanton;
    private javax.swing.JLabel txtCodigoProvincia;
    private javax.swing.JTextField txtFechaNacimiento1;
    private javax.swing.JTextField txtMesa1;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtRecinto1;
    // End of variables declaration//GEN-END:variables
}
